=== houaELM02/GestionScolaire_XML/AffichageGinf31/SchemaAffichage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:simpleType name="NoteType">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="20"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="NotesType">
        <xs:sequence>
            <xs:element name="CNE" type="xs:string"/>
            <xs:element name="Nom" type="xs:string"/>
            <xs:element name="Prenom" type="xs:string"/>
            <xs:element name="JAVA" type="NoteType"/>
            <xs:element name="XML" type="NoteType"/>
           
        </xs:sequence>
    </xs:complexType>
    <!-- Déclaration du type complexe pour la liste des étudiants -->
    <xs:complexType name="notes">
        <xs:sequence>
            <xs:element name="Note" type="NotesType" minOccurs="1"  maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    
    
    <xs:complexType name="NotesGinf31">
        <xs:sequence>
            <xs:element name="logoEnsa" type="xs:anyType" minOccurs="0"/>
            <xs:element name="logoUae" type="xs:anyType" minOccurs="0"/>
            <xs:element name="classe" type="xs:string"/>
            <xs:element name="annee" type="xs:string"/>
            <xs:element name="Notes" type="notes"/>
           
        </xs:sequence>
    </xs:complexType>
    
    <!-- Racine du schéma -->
    <xs:element name="AffichageNotes" type="NotesGinf31"/>
    
    
    
    
</xs:schema>

=== houaELM02/GestionScolaire_XML/AffichageGinf31/AffichageGINF31.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="AffichageGINF31.xsl"?>
<AffichageNotes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="SchemaAffichage.xsd">
	<logoEnsa uri="logoEnsat.png"/>
	<logoUae uri="logoUae.png"/>
	<classe>GINF2</classe>
	<annee>2023/2024</annee>
	<Notes>
	<Note>
		<CNE>20000773</CNE>
		<Nom>ABETIOU</Nom>
		<Prenom>SOFIANE</Prenom>
		<JAVA>16</JAVA>
		<XML>10</XML>
	</Note>
	<Note>
		<CNE>19001211</CNE>
		<Nom>ACHERNAN</Nom>
		<Prenom>MOHAMED</Prenom>
		<JAVA>4</JAVA>
		<XML>6</XML>
	</Note>
	<Note>
		<CNE>19001137</CNE>
		<Nom>AFOUD</Nom>
		<Prenom>HIND</Prenom>
		<JAVA>12</JAVA>
		<XML>12</XML>
	</Note>
	<Note>
		<CNE>20000734</CNE>
		<Nom>AIT OUKHADOU</Nom>
		<Prenom>SELMA</Prenom>
		<JAVA>18</JAVA>
		<XML>18</XML>
	</Note>
	<Note>
		<CNE>20000761</CNE>
		<Nom>AKIIRNE</Nom>
		<Prenom>AMAL</Prenom>
		<JAVA>10</JAVA>
		<XML>8</XML>
	</Note>
	<Note>
		<CNE>19001276</CNE>
		<Nom>AMHAOUECH</Nom>
		<Prenom>WIAM</Prenom>
		<JAVA>13</JAVA>
		<XML>14</XML>
	</Note>
	<Note>
		<CNE>20001244</CNE>
		<Nom>AMINE</Nom>
		<Prenom>TAHA</Prenom>
		<JAVA>9</JAVA>
		<XML>3</XML>
	</Note>
	<Note>
		<CNE>20000493</CNE>
		<Nom>ARRAB</Nom>
		<Prenom>HAFSA</Prenom>
		<JAVA>8</JAVA>
		<XML>11</XML>
	</Note>
	<Note>
		<CNE>20006988</CNE>
		<Nom>BAJJI</Nom>
		<Prenom>AMINE</Prenom>
		<JAVA>17</JAVA>
		<XML>15</XML>
	</Note>
	<Note>
		<CNE>20007078</CNE>
		<Nom>BENAMRI</Nom>
		<Prenom>AYMANE</Prenom>
		<JAVA>11</JAVA>
		<XML>7</XML>
	</Note>
	<Note>
		<CNE>20000758</CNE>
		<Nom>BENATTOU</Nom>
		<Prenom>IHSANE</Prenom>
		<JAVA>15</JAVA>
		<XML>13</XML>
	</Note>
	<Note>
		<CNE>20000757</CNE>
		<Nom>BENATTOU</Nom>
		<Prenom>IMANE</Prenom>
		<JAVA>9</JAVA>
		<XML>17</XML>
	</Note>
	<Note>
		<CNE>19002165</CNE>
		<Nom>BENTOUFILE</Nom>
		<Prenom>OUSSAMA</Prenom>
		<JAVA>20</JAVA>
		<XML>9</XML>
	</Note>
	<Note>
		<CNE>20000730</CNE>
		<Nom>BOUALI</Nom>
		<Prenom>MAROUA</Prenom>
		<JAVA>7</JAVA>
		<XML>20</XML>
	</Note>
	<Note>
		<CNE>20002424</CNE>
		<Nom>BOUKTAIB</Nom>
		<Prenom>SOUFIAN</Prenom>
		<JAVA>16</JAVA>
		<XML>10</XML>
	</Note>
	<Note>
		<CNE>20000771</CNE>
		<Nom>BOULAID</Nom>
		<Prenom>SARA</Prenom>
		<JAVA>12</JAVA>
		<XML>16</XML>
	</Note>
	<Note>
		<CNE>20007025</CNE>
		<Nom>CHANAA</Nom>
		<Prenom>AIMANE</Prenom>
		<JAVA>14</JAVA>
		<XML>12</XML>
	</Note>
	<Note>
		<CNE>20007161</CNE>
		<Nom>CHATT</Nom>
		<Prenom>ANAS</Prenom>
		<JAVA>10</JAVA>
		<XML>14</XML>
	</Note>
	<Note>
		<CNE>20004313</CNE>
		<Nom>DAHRABOU</Nom>
		<Prenom>DOHA</Prenom>
		<JAVA>18</JAVA>
		<XML>8</XML>
	</Note>
	<Note>
		<CNE>20007051</CNE>
		<Nom>DAOUDI</Nom>
		<Prenom>AYA</Prenom>
		<JAVA>11</JAVA>
		<XML>18</XML>
	</Note>
	<Note>
		<CNE>20002432</CNE>
		<Nom>ECHBERAAL</Nom>
		<Prenom>ANASS</Prenom>
		<JAVA>13</JAVA>
		<XML>11</XML>
	</Note>
	<Note>
		<CNE>20002251</CNE>
		<Nom>EL AALOUCH</Nom>
		<Prenom>MOHAMMED YASSINE</Prenom>
		<JAVA>15</JAVA>
		<XML>13</XML>
	</Note>
	<Note>
		<CNE>20002670</CNE>
		<Nom>EL ASSIRI</Nom>
		<Prenom>AHLAM</Prenom>
		<JAVA>9</JAVA>
		<XML>15</XML>
	</Note>
	<Note>
		<CNE>20000742</CNE>
		<Nom>EL AZOUAN</Nom>
		<Prenom>AYA</Prenom>
		<JAVA>17</JAVA>
		<XML>19</XML>
	</Note>
	<Note>
		<CNE>20000741</CNE>
		<Nom>EL BAGHDADI</Nom>
		<Prenom>NADA</Prenom>
		<JAVA>8</JAVA>
		<XML>17</XML>
	</Note>
	<Note>
		<CNE>20000775</CNE>
		<Nom>EL BARAKA</Nom>
		<Prenom>NOUHAILA</Prenom>
		<JAVA>19</JAVA>
		<XML>7</XML>
	</Note>
	<Note>
		<CNE>19001439</CNE>
		<Nom>EL FICH</Nom>
		<Prenom>RIHAB</Prenom>
		<JAVA>10</JAVA>
		<XML>19</XML>
	</Note>
	<Note>
		<CNE>20000780</CNE>
		<Nom>EL HABTI</Nom>
		<Prenom>NAJOUA</Prenom>
		<JAVA>14</JAVA>
		<XML>10</XML>
	</Note>
	<Note>
		<CNE>20003925</CNE>
		<Nom>EL HADDAD</Nom>
		<Prenom>MOHAMED</Prenom>
		<JAVA>12</JAVA>
		<XML>14</XML>
	</Note>
	<Note>
		<CNE>20000755</CNE>
		<Nom>EL HARRACHY</Nom>
		<Prenom>ABDERRAHMANE</Prenom>
		<JAVA>16</JAVA>
		<XML>12</XML>
	</Note>
	<Note>
		<CNE>20000716</CNE>
		<Nom>EL MAFTOUHI</Nom>
		<Prenom>BILAL</Prenom>
		<JAVA>11</JAVA>
		<XML>16</XML>
	</Note>
	<Note>
		<CNE>18008815</CNE>
		<Nom>EL MAIMOUNI</Nom>
		<Prenom>MOHAMED AMINE</Prenom>
		<JAVA>13</JAVA>
		<XML>11</XML>
	</Note>
	<Note>
		<CNE>20006989</CNE>
		<Nom>EL MOUMOUHI</Nom>
		<Prenom>HOUDA</Prenom>
		<JAVA>17</JAVA>
		<XML>19</XML>
	</Note>
	<Note>
		<CNE>20007067</CNE>
		<Nom>EL OMARI</Nom>
		<Prenom>IMANE</Prenom>
		<JAVA>9</JAVA>
		<XML>15</XML>
	</Note>
	<Note>
		<CNE>19001413</CNE>
		<Nom>EL YAMLAHI</Nom>
		<Prenom>AICHA</Prenom>
		<JAVA>18</JAVA>
		<XML>9</XML>
	</Note>
	<Note>
		<CNE>17004026</CNE>
		<Nom>EL YAZGHI</Nom>
		<Prenom>MARYEM</Prenom>
		<JAVA>7</JAVA>
		<XML>18</XML>
	</Note>
	<Note>
		<CNE>20000759</CNE>
		<Nom>ENNAJARI</Nom>
		<Prenom>OUMAIMA</Prenom>
		<JAVA>20</JAVA>
		<XML>8</XML>
	</Note>
	<Note>
		<CNE>19005693</CNE>
		<Nom>ESSAIH</Nom>
		<Prenom>ASMAE</Prenom>
		<JAVA>8</JAVA>
		<XML>20</XML>
	</Note>
	<Note>
		<CNE>19005680</CNE>
		<Nom>FAROUK</Nom>
		<Prenom>ZAKARIA</Prenom>
		<JAVA>14</JAVA>
		<XML>10</XML>
	</Note>
	<Note>
		<CNE>20000777</CNE>
		<Nom>GLIOUAL</Nom>
		<Prenom>YASSINE</Prenom>
		<JAVA>12</JAVA>
		<XML>14</XML>
	</Note>
	<Note>
		<CNE>19005656</CNE>
		<Nom>GOMAIRI</Nom>
		<Prenom>HAMZA</Prenom>
		<JAVA>16</JAVA>
		<XML>12</XML>
	</Note>
	<Note>
		<CNE>19006584</CNE>
		<Nom>HAJI</Nom>
		<Prenom>OTMANE</Prenom>
		<JAVA>10</JAVA>
		<XML>16</XML>
	</Note>
	<Note>
		<CNE>20002433</CNE>
		<Nom>HAMDAN</Nom>
		<Prenom>KARIMA</Prenom>
		<JAVA>13</JAVA>
		<XML>7</XML>
	</Note>
	<Note>
		<CNE>20002532</CNE>
		<Nom>HARRAK</Nom>
		<Prenom>YOUSSEF</Prenom>
		<JAVA>15</JAVA>
		<XML>13</XML>
	</Note>
	<Note>
		<CNE>20000763</CNE>
		<Nom>HAYAOUI</Nom>
		<Prenom>MOUAD</Prenom>
		<JAVA>9</JAVA>
		<XML>15</XML>
	</Note>
	<Note>
		<CNE>20000740</CNE>
		<Nom>HIMMI</Nom>
		<Prenom>HAJAR</Prenom>
		<JAVA>17</JAVA>
		<XML>9</XML>
	</Note>
	<Note>
		<CNE>20002137</CNE>
		<Nom>IDRISSI</Nom>
		<Prenom>YASSINE</Prenom>
		<JAVA>11</JAVA>
		<XML>17</XML>
	</Note>
	<Note>
		<CNE>20006985</CNE>
		<Nom>JAADA</Nom>
		<Prenom>ZAHAIRA</Prenom>
		<JAVA>19</JAVA>
		<XML>11</XML>
	</Note>
	<Note>
		<CNE>20002554</CNE>
		<Nom>KACHAR</Nom>
		<Prenom>NABIL</Prenom>
		<JAVA>8</JAVA>
		<XML>19</XML>
	</Note>
	<Note>
		<CNE>20009742</CNE>
		<Nom>KDIDAR</Nom>
		<Prenom>HAJAR</Prenom>
		<JAVA>14</JAVA>
		<XML>8</XML>
	</Note>
	<Note>
		<CNE>19006706</CNE>
		<Nom>KEFFAOUI</Nom>
		<Prenom>NOHA</Prenom>
		<JAVA>12</JAVA>
		<XML>14</XML>
	</Note>
	<Note>
		<CNE>20006930</CNE>
		<Nom>KHALLOUFI</Nom>
		<Prenom>AYA</Prenom>
		<JAVA>16</JAVA>
		<XML>12</XML>
	</Note>
	<Note>
		<CNE>20000754</CNE>
		<Nom>LAABADI</Nom>
		<Prenom>HOUDA</Prenom>
		<JAVA>10</JAVA>
		<XML>16</XML>
	</Note>
	<Note>
		<CNE>19002804</CNE>
		<Nom>LAHOIENI</Nom>
		<Prenom>ABDERRAHIM</Prenom>
		<JAVA>13</JAVA>
		<XML>10</XML>
	</Note>
	<Note>
		<CNE>19001375</CNE>
		<Nom>LAKRAMAT</Nom>
		<Prenom>HASNAE</Prenom>
		<JAVA>15</JAVA>
		<XML>13</XML>
	</Note>
	<Note>
		<CNE>20000731</CNE>
		<Nom>MOUNTASSIR</Nom>
		<Prenom>REDA</Prenom>
		<JAVA>9</JAVA>
		<XML>15</XML>
	</Note>
	<Note>
		<CNE>20000513</CNE>
		<Nom>NAYMA</Nom>
		<Prenom>OMAYMA</Prenom>
		<JAVA>17</JAVA>
		<XML>9</XML>
	</Note>
	<Note>
		<CNE>19006284</CNE>
		<Nom>RAYES</Nom>
		<Prenom>ABDELKOUDOUS</Prenom>
		<JAVA>11</JAVA>
		<XML>18</XML>
	</Note>
	<Note>
		<CNE>20000721</CNE>
		<Nom>SAMADI</Nom>
		<Prenom>IMAD</Prenom>
		<JAVA>19</JAVA>
		<XML>11</XML>
	</Note>
	<Note>
		<CNE>20002123</CNE>
		<Nom>ZAOUI</Nom>
		<Prenom>OUSSAMA</Prenom>
		<JAVA>8</JAVA>
		<XML>19</XML>
	</Note>
	<Note>
		<CNE>20000491</CNE>
		<Nom>ZOUAKI</Nom>
		<Prenom>MARIA</Prenom>
		<JAVA>14</JAVA>
		<XML>8</XML>
	</Note>
	</Notes>
</AffichageNotes>
