=== houaELM02/GestionScolaire_XML/Affichage de toute la classe/AffichageClasse.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ReleveNotes (logoEnsa ,logoUae ,classe , annee , Etudiants, Modules) >
<!ELEMENT logoEnsa (#PCDATA)>
<!ATTLIST logoEnsa 
                 uri CDATA #REQUIRED>
<!ELEMENT logoUae (#PCDATA) >
<!ATTLIST logoUae
                 uri CDATA #REQUIRED>
<!ELEMENT classe (#PCDATA) >
<!ELEMENT annee (#PCDATA) >
<!ELEMENT Etudiants (Etudiant+) >
<!ELEMENT Etudiant (CNE , Nom , Prenom , Notes) >
<!ELEMENT CNE (#PCDATA) >
<!ELEMENT Nom (#PCDATA)>
<!ELEMENT Prenom (#PCDATA)>
<!ELEMENT Notes (GINF31 , GINF32 ,GINF33 ,GINF34 ,GINF35,GINF36,GINF41 ,GINF42,GINF43,GINF44 ,GINF45 ,GINF46) >
<!ELEMENT GINF31 (#PCDATA) >
<!ELEMENT GINF32 (#PCDATA) >
<!ELEMENT GINF33 (#PCDATA) >
<!ELEMENT GINF34 (#PCDATA) >
<!ELEMENT GINF35 (#PCDATA) >
<!ELEMENT GINF36 (#PCDATA) >
<!ELEMENT GINF41 (#PCDATA) >
<!ELEMENT GINF42 (#PCDATA) >
<!ELEMENT GINF43 (#PCDATA) >
<!ELEMENT GINF44 (#PCDATA) >
<!ELEMENT GINF45 (#PCDATA) >
<!ELEMENT GINF46 (#PCDATA) >
<!ELEMENT Modules (Module+)>
<!ELEMENT  Module (#PCDATA) >
<!ATTLIST Module 
                code CDATA #REQUIRED>

=== houaELM02/GestionScolaire_XML/Affichage de toute la classe/AffichageClasseInf2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ReleveNotes SYSTEM "AffichageClasse.dtd">

<?xml-stylesheet type="text/xsl" href="AffichageGinf2.xsl"?>
<ReleveNotes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="affichageClasse.xsd">	
		<logoEnsa uri="ensat.png"/>
		<logoUae uri="logoUae.jpeg"/>
	<classe>2 ème année Génie Informatique</classe>
	<annee>2024/2023</annee>
  <Etudiants>
	<Etudiant>
		<CNE>20000773</CNE>
		<Nom>ABETIOU</Nom>
		<Prenom>SOFIANE</Prenom>
		<Notes>
			<GINF31>13</GINF31>
			<GINF32>14</GINF32>
			<GINF33>14</GINF33>
			<GINF34>9</GINF34>
			<GINF35>15</GINF35>
			<GINF36>11</GINF36>
			<GINF41>13</GINF41>
			<GINF42>14</GINF42>
			<GINF43>9</GINF43>
			<GINF44>15</GINF44>
			<GINF45>13</GINF45>
			<GINF46>13</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>19001211</CNE>
		<Nom>ACHERNAN</Nom>
		<Prenom>MOHAMED</Prenom>
		<Notes>
			<GINF31>15</GINF31>
			<GINF32>8</GINF32>
			<GINF33>8</GINF33>
			<GINF34>15</GINF34>
			<GINF35>10</GINF35>
			<GINF36>16</GINF36>
			<GINF41>8</GINF41>
			<GINF42>8</GINF42>
			<GINF43>15</GINF43>
			<GINF44>10</GINF44>
			<GINF45>8</GINF45>
			<GINF46>15</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>19001137</CNE>
		<Nom>AFOUD</Nom>
		<Prenom>HIND</Prenom>
		<Notes>
			<GINF31>12</GINF31>
			<GINF32>16</GINF32>
			<GINF33>16</GINF33>
			<GINF34>11</GINF34>
			<GINF35>16</GINF35>
			<GINF36>10</GINF36>
			<GINF41>15</GINF41>
			<GINF42>16</GINF42>
			<GINF43>11</GINF43>
			<GINF44>16</GINF44>
			<GINF45>15</GINF45>
			<GINF46>12</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20000734</CNE>
		<Nom>AIT OUKHADOU</Nom>
		<Prenom>SELMA</Prenom>
		<Notes>
			<GINF31>18</GINF31>
			<GINF32>12</GINF32>
			<GINF33>12</GINF33>
			<GINF34>17</GINF34>
			<GINF35>12</GINF35>
			<GINF36>14</GINF36>
			<GINF41>11</GINF41>
			<GINF42>12</GINF42>
			<GINF43>17</GINF43>
			<GINF44>12</GINF44>
			<GINF45>11</GINF45>
			<GINF46>18</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20000761</CNE>
		<Nom>AKIIRNE</Nom>
		<Prenom>AMAL</Prenom>
		<Notes>
			<GINF31>9</GINF31>
			<GINF32>18</GINF32>
			<GINF33>18</GINF33>
			<GINF34>7</GINF34>
			<GINF35>18</GINF35>
			<GINF36>8</GINF36>
			<GINF41>18</GINF41>
			<GINF42>18</GINF42>
			<GINF43>7</GINF43>
			<GINF44>18</GINF44>
			<GINF45>18</GINF45>
			<GINF46>9</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>19001276</CNE>
		<Nom>AMHAOUECH</Nom>
		<Prenom>WIAM</Prenom>
		<Notes>
			<GINF31>13.5</GINF31>
			<GINF32>10</GINF32>
			<GINF33>10</GINF33>
			<GINF34>13</GINF34>
			<GINF35>11</GINF35>
			<GINF36>15</GINF36>
			<GINF41>12</GINF41>
			<GINF42>10</GINF42>
			<GINF43>13</GINF43>
			<GINF44>11</GINF44>
			<GINF45>12</GINF45>
			<GINF46>13.5</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20001244</CNE>
		<Nom>AMINE</Nom>
		<Prenom>TAHA</Prenom>
		<Notes>
			<GINF31>19</GINF31>
			<GINF32>13</GINF32>
			<GINF33>13</GINF33>
			<GINF34>18</GINF34>
			<GINF35>14</GINF35>
			<GINF36>9</GINF36>
			<GINF41>16</GINF41>
			<GINF42>13</GINF42>
			<GINF43>18</GINF43>
			<GINF44>14</GINF44>
			<GINF45>16</GINF45>
			<GINF46>19</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20000493</CNE>
		<Nom>ARRAB</Nom>
		<Prenom>HAFSA</Prenom>
		<Notes>
			<GINF31>9.5</GINF31>
			<GINF32>9</GINF32>
			<GINF33>9</GINF33>
			<GINF34>10</GINF34>
			<GINF35>8</GINF35>
			<GINF36>17</GINF36>
			<GINF41>10</GINF41>
			<GINF42>9</GINF42>
			<GINF43>10</GINF43>
			<GINF44>8</GINF44>
			<GINF45>10</GINF45>
			<GINF46>9.5</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20006988</CNE>
		<Nom>BAJJI</Nom>
		<Prenom>AMINE</Prenom>
		<Notes>
			<GINF31>16</GINF31>
			<GINF32>15</GINF32>
			<GINF33>15</GINF33>
			<GINF34>14</GINF34>
			<GINF35>17</GINF35>
			<GINF36>12</GINF36>
			<GINF41>14</GINF41>
			<GINF42>15</GINF42>
			<GINF43>14</GINF43>
			<GINF44>17</GINF44>
			<GINF45>14</GINF45>
			<GINF46>16</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20007078</CNE>
		<Nom>BENAMRI</Nom>
		<Prenom>AYMANE</Prenom>
		<Notes>
			<GINF31>9</GINF31>
			<GINF32>11</GINF32>
			<GINF33>11</GINF33>
			<GINF34>8</GINF34>
			<GINF35>9</GINF35>
			<GINF36>7</GINF36>
			<GINF41>9</GINF41>
			<GINF42>11</GINF42>
			<GINF43>8</GINF43>
			<GINF44>9</GINF44>
			<GINF45>9</GINF45>
			<GINF46>9</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20000758</CNE>
		<Nom>BENATTOU</Nom>
		<Prenom>IHSANE</Prenom>
		<Notes>
			<GINF31>14</GINF31>
			<GINF32>17</GINF32>
			<GINF33>17</GINF33>
			<GINF34>16</GINF34>
			<GINF35>13</GINF35>
			<GINF36>18</GINF36>
			<GINF41>17</GINF41>
			<GINF42>17</GINF42>
			<GINF43>16</GINF43>
			<GINF44>13</GINF44>
			<GINF45>17</GINF45>
			<GINF46>14</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20000757</CNE>
		<Nom>BENATTOU</Nom>
		<Prenom>IMANE</Prenom>
		<Notes>
			<GINF31>13</GINF31>
			<GINF32>7</GINF32>
			<GINF33>7</GINF33>
			<GINF34>12</GINF34>
			<GINF35>19</GINF35>
			<GINF36>13</GINF36>
			<GINF41>7</GINF41>
			<GINF42>7</GINF42>
			<GINF43>12</GINF43>
			<GINF44>19</GINF44>
			<GINF45>7</GINF45>
			<GINF46>13</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>19002165</CNE>
		<Nom>BENTOUFILE</Nom>
		<Prenom>OUSSAMA</Prenom>
		<Notes>
			<GINF31>14.5</GINF31>
			<GINF32>19</GINF32>
			<GINF33>19</GINF33>
			<GINF34>19</GINF34>
			<GINF35>10</GINF35>
			<GINF36>19</GINF36>
			<GINF41>19</GINF41>
			<GINF42>19</GINF42>
			<GINF43>19</GINF43>
			<GINF44>10</GINF44>
			<GINF45>19</GINF45>
			<GINF46>14.5</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20000730</CNE>
		<Nom>BOUALI</Nom>
		<Prenom>MAROUA</Prenom>
		<Notes>
			<GINF31>13.5</GINF31>
			<GINF32>10</GINF32>
			<GINF33>10</GINF33>
			<GINF34>9</GINF34>
			<GINF35>15</GINF35>
			<GINF36>11</GINF36>
			<GINF41>11</GINF41>
			<GINF42>10</GINF42>
			<GINF43>9</GINF43>
			<GINF44>15</GINF44>
			<GINF45>11</GINF45>
			<GINF46>13.5</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20002424</CNE>
		<Nom>BOUKTAIB</Nom>
		<Prenom>SOUFIAN</Prenom>
		<Notes>
			<GINF31>13</GINF31>
			<GINF32>14</GINF32>
			<GINF33>14</GINF33>
			<GINF34>15</GINF34>
			<GINF35>12</GINF35>
			<GINF36>16</GINF36>
			<GINF41>13</GINF41>
			<GINF42>14</GINF42>
			<GINF43>15</GINF43>
			<GINF44>12</GINF44>
			<GINF45>13</GINF45>
			<GINF46>13</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20000771</CNE>
		<Nom>BOULAID</Nom>
		<Prenom>SARA</Prenom>
		<Notes>
			<GINF31>14</GINF31>
			<GINF32>12</GINF32>
			<GINF33>12</GINF33>
			<GINF34>11</GINF34>
			<GINF35>16</GINF35>
			<GINF36>10</GINF36>
			<GINF41>15</GINF41>
			<GINF42>12</GINF42>
			<GINF43>11</GINF43>
			<GINF44>16</GINF44>
			<GINF45>15</GINF45>
			<GINF46>14</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20007025</CNE>
		<Nom>CHANAA</Nom>
		<Prenom>AIMANE</Prenom>
		<Notes>
			<GINF31>13</GINF31>
			<GINF32>16</GINF32>
			<GINF33>16</GINF33>
			<GINF34>13</GINF34>
			<GINF35>8</GINF35>
			<GINF36>14</GINF36>
			<GINF41>8</GINF41>
			<GINF42>16</GINF42>
			<GINF43>13</GINF43>
			<GINF44>8</GINF44>
			<GINF45>8</GINF45>
			<GINF46>13</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20007161</CNE>
		<Nom>CHATT</Nom>
		<Prenom>ANAS</Prenom>
		<Notes>
			<GINF31>12</GINF31>
			<GINF32>8</GINF32>
			<GINF33>8</GINF33>
			<GINF34>7</GINF34>
			<GINF35>18</GINF35>
			<GINF36>8</GINF36>
			<GINF41>16</GINF41>
			<GINF42>8</GINF42>
			<GINF43>7</GINF43>
			<GINF44>18</GINF44>
			<GINF45>16</GINF45>
			<GINF46>12</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20004313</CNE>
		<Nom>DAHRABOU</Nom>
		<Prenom>DOHA</Prenom>
		<Notes>
			<GINF31>13</GINF31>
			<GINF32>18</GINF32>
			<GINF33>18</GINF33>
			<GINF34>17</GINF34>
			<GINF35>13</GINF35>
			<GINF36>15</GINF36>
			<GINF41>10</GINF41>
			<GINF42>18</GINF42>
			<GINF43>17</GINF43>
			<GINF44>13</GINF44>
			<GINF45>10</GINF45>
			<GINF46>13</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20007051</CNE>
		<Nom>DAOUDI</Nom>
		<Prenom>AYA</Prenom>
		<Notes>
			<GINF31>14.5</GINF31>
			<GINF32>11</GINF32>
			<GINF33>11</GINF33>
			<GINF34>10</GINF34>
			<GINF35>14</GINF35>
			<GINF36>12</GINF36>
			<GINF41>14</GINF41>
			<GINF42>11</GINF42>
			<GINF43>10</GINF43>
			<GINF44>14</GINF44>
			<GINF45>14</GINF45>
			<GINF46>14.5</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20002432</CNE>
		<Nom>ECHBERAAL</Nom>
		<Prenom>ANASS</Prenom>
		<Notes>
			<GINF31>12</GINF31>
			<GINF32>13</GINF32>
			<GINF33>13</GINF33>
			<GINF34>12</GINF34>
			<GINF35>9</GINF35>
			<GINF36>13</GINF36>
			<GINF41>9</GINF41>
			<GINF42>13</GINF42>
			<GINF43>12</GINF43>
			<GINF44>9</GINF44>
			<GINF45>9</GINF45>
			<GINF46>12</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20002251</CNE>
		<Nom>EL AALOUCH</Nom>
		<Prenom>MOHAMMED YASSINE</Prenom>
		<Notes>
			<GINF31>14</GINF31>
			<GINF32>15</GINF32>
			<GINF33>15</GINF33>
			<GINF34>14</GINF34>
			<GINF35>17</GINF35>
			<GINF36>9</GINF36>
			<GINF41>18</GINF41>
			<GINF42>15</GINF42>
			<GINF43>14</GINF43>
			<GINF44>17</GINF44>
			<GINF45>18</GINF45>
			<GINF46>14</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20002670</CNE>
		<Nom>EL ASSIRI</Nom>
		<Prenom>AHLAM</Prenom>
		<Notes>
			<GINF31>12</GINF31>
			<GINF32>9</GINF32>
			<GINF33>9</GINF33>
			<GINF34>8</GINF34>
			<GINF35>11</GINF35>
			<GINF36>17</GINF36>
			<GINF41>12</GINF41>
			<GINF42>9</GINF42>
			<GINF43>8</GINF43>
			<GINF44>11</GINF44>
			<GINF45>12</GINF45>
			<GINF46>12</GINF46>
		</Notes>
	</Etudiant>
	<Etudiant>
		<CNE>20000742</CNE>
		<Nom>EL AZOUAN</Nom>
		<Prenom>AYA</Prenom>
		<Notes>
			<GINF31>18</GINF31>
			<GINF32>17</GINF32>
			<GINF33>17</GINF33>
